AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Slack Notifier stack'

Parameters:

  SlackApiToken:
    Description: 'The Slack webhook token that will be used by the Notifier function'
    Type: String
    NoEcho: true
    Default: 'empty'

  SlackNotificationChannel:
    Description: 'The Slack channel the notifications will be sent to'
    Type: String
    Default: 'empty'

  SlackWebHookUrl:
    Description: 'The Slack 2ebhook URL the function will send our notifications to'
    Type: String
    Default: 'empty'


Resources:

  SlackTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: 'Slack Webhook token used to authenticate to the Slack API'
      Name: 'SlackApiToken'
      SecretString: !Ref SlackApiToken

  NotifierLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notifier.notify
      CodeUri: ../src
      Runtime: python3.8

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: 'NotifierLambdaPolicy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            - sns:Subscribe
            Resource: '*'
    
  NotifierSnsTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: 'Slack Notifier'
      TopicName: 'SlackNotifier'
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt NotifierLambda.Arn
